-- Create a schema for source-preserving raw data.
CREATE SCHEMA IF NOT EXISTS raw;

-- Store the CMS source columns as TEXT to preserve original values,
-- including privacy-suppressed values represented by '*'.
CREATE TABLE raw.medicare_monthly_enrollment (
    year TEXT,
    month TEXT,
    bene_geo_lvl TEXT,
    bene_state_abrvtn TEXT,
    bene_state_desc TEXT,
    bene_county_desc TEXT,
    bene_fips_cd TEXT,
    tot_benes TEXT,
    orgnl_mdcr_benes TEXT,
    ma_and_oth_benes TEXT,
    aged_tot_benes TEXT,
    aged_esrd_benes TEXT,
    aged_no_esrd_benes TEXT,
    dsbld_tot_benes TEXT,
    dsbld_esrd_and_esrd_only_benes TEXT,
    dsbld_no_esrd_benes TEXT,
    male_tot_benes TEXT,
    female_tot_benes TEXT,
    white_tot_benes TEXT,
    black_tot_benes TEXT,
    api_tot_benes TEXT,
    hspnc_tot_benes TEXT,
    natind_tot_benes TEXT,
    othr_tot_benes TEXT,
    age_lt_25_benes TEXT,
    age_25_to_44_benes TEXT,
    age_45_to_64_benes TEXT,
    age_65_to_69_benes TEXT,
    age_70_to_74_benes TEXT,
    age_75_to_79_benes TEXT,
    age_80_to_84_benes TEXT,
    age_85_to_89_benes TEXT,
    age_90_to_94_benes TEXT,
    age_gt_94_benes TEXT,
    dual_tot_benes TEXT,
    full_dual_tot_benes TEXT,
    part_dual_tot_benes TEXT,
    nodual_tot_benes TEXT,
    qmb_only_benes TEXT,
    qmb_plus_benes TEXT,
    slmb_only_benes TEXT,
    slmb_plus_benes TEXT,
    qdwi_qi_benes TEXT,
    othr_full_dual_mdcd_benes TEXT,
    a_b_tot_benes TEXT,
    a_b_orgnl_mdcr_benes TEXT,
    a_b_ma_and_oth_benes TEXT,
    a_tot_benes TEXT,
    a_orgnl_mdcr_benes TEXT,
    a_ma_and_oth_benes TEXT,
    b_tot_benes TEXT,
    b_orgnl_mdcr_benes TEXT,
    b_ma_and_oth_benes TEXT,
    prscrptn_drug_tot_benes TEXT,
    prscrptn_drug_pdp_benes TEXT,
    prscrptn_drug_mapd_benes TEXT,
    prscrptn_drug_deemed_eligible_full_lis_benes TEXT,
    prscrptn_drug_full_lis_benes TEXT,
    prscrptn_drug_partial_lis_benes TEXT,
    prscrptn_drug_no_lis_benes TEXT
);